// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEC-BZD-w-JRj3_ZVYY5etmbslVJKGWZQ',
    appId: '1:855636559547:web:23d51e9816cdea46a34b9e',
    messagingSenderId: '855636559547',
    projectId: 'figai-3f060',
    authDomain: 'figai-3f060.firebaseapp.com',
    storageBucket: 'figai-3f060.firebasestorage.app',
    measurementId: 'G-1EL8KFFL4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE_usLAzsdEg6reIK4wQ3DJNApqRYaTu0',
    appId: '1:855636559547:android:f3383d61c3e62dbea34b9e',
    messagingSenderId: '855636559547',
    projectId: 'figai-3f060',
    storageBucket: 'figai-3f060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc84Zb692-9pBbAOjjnxmejT9_yYAWXfk',
    appId: '1:855636559547:ios:9cd5e3a813ac16afa34b9e',
    messagingSenderId: '855636559547',
    projectId: 'figai-3f060',
    storageBucket: 'figai-3f060.firebasestorage.app',
    iosBundleId: 'com.example.figAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc84Zb692-9pBbAOjjnxmejT9_yYAWXfk',
    appId: '1:855636559547:ios:9cd5e3a813ac16afa34b9e',
    messagingSenderId: '855636559547',
    projectId: 'figai-3f060',
    storageBucket: 'figai-3f060.firebasestorage.app',
    iosBundleId: 'com.example.figAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEC-BZD-w-JRj3_ZVYY5etmbslVJKGWZQ',
    appId: '1:855636559547:web:9e7daa73abea6f6ca34b9e',
    messagingSenderId: '855636559547',
    projectId: 'figai-3f060',
    authDomain: 'figai-3f060.firebaseapp.com',
    storageBucket: 'figai-3f060.firebasestorage.app',
    measurementId: 'G-4Z504YJYCM',
  );
}
